#!/usr/bin/env python3
"""
intro_draft.py — Draf Introduction paper (EN) dengan hook "fear-as-demand" + kasus Soraya.

Angka diambil OTOMATIS dari hasil terbaru (tidak ada angka karangan):
  data/films_clean.csv                        penonton bersumber
  results/correlation_*/spearman.csv          Spearman eksak
  results/robust_*/robustness.csv             bootstrap CI, Bonferroni, BH, parsial
  results/model_*/model.json                  LOOCV vs baseline
  results/sentiment_*/crosstab_*.csv, run_info.json   bias IndoBERT vs leksikon
  annotation/validation_result.json           status label manusia / kappa LLM

Keluaran: docs/papers/introduction_draft.md
Pakai:    ./bit intro
"""
import csv, glob, json, os, datetime

BASE = os.path.dirname(os.path.realpath(__file__))
OUT = os.path.join(BASE, "docs", "papers", "introduction_draft.md")


def latest(pattern):
    c = sorted(glob.glob(os.path.join(BASE, pattern)))
    return c[-1] if c else None


def rows(path):
    if not path or not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def jload(path):
    if not path or not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def num(x, d=None):
    try:
        return float(x)
    except (TypeError, ValueError):
        return d


def fmt_int(x):
    return f"{int(x):,}" if x is not None else "[n/a]"


def main():
    used = []  # jejak sumber angka

    films = rows(os.path.join(BASE, "data", "films_clean.csv"))
    used.append("data/films_clean.csv")
    by_id = {r["film_id"]: r for r in films}
    n_films = len(films)

    def viewers(fid):
        r = by_id.get(fid)
        return (num(r["penonton"]), r.get("is_final") in ("1", "True", "true")) if r else (None, None)

    s18, _ = viewers("suzzanna-2018")
    s23, _ = viewers("suzzanna-2023")
    s26, s26_final = viewers("suzzanna-2026")
    rs, rs_final = viewers("racun-sangga-2024")
    ratio = (s18 / rs) if (s18 and rs) else None
    studios = sorted({r["rumah_produksi"].split(" (")[0].split(" /")[0] for r in films} - {"Soraya Intercine Films", "Hitmaker Studios"})

    # korelasi & robust
    rob_path = latest("results/robust_*/robustness.csv")
    rob = {r["metrik"]: r for r in rows(rob_path)}
    if rob_path:
        used.append(os.path.relpath(rob_path, BASE))
    likes = rob.get("likes_total", {})
    tr = rob.get("trends_pra_rilis", {})
    sent_rhos = [abs(num(r["rho"], 0)) for k, r in rob.items() if r.get("jenis") == "sentimen"]
    max_sent = max(sent_rhos) if sent_rhos else None

    # model
    mdl_path = latest("results/model_*/model.json")
    mdl = jload(mdl_path)
    if mdl_path:
        used.append(os.path.relpath(mdl_path, BASE))

    # bias sentimen
    sdir = latest("results/sentiment_*")
    info = jload(os.path.join(sdir, "run_info.json")) if sdir else {}
    ct = {r["sent_lexicon"]: r for r in rows(os.path.join(sdir, "crosstab_lexicon_vs_indobert.csv"))} if sdir else {}
    if sdir:
        used.append(os.path.relpath(sdir, BASE) + "/{run_info.json,crosstab_lexicon_vs_indobert.csv}")
    n_com = info.get("n_comments")
    allrow = ct.get("All", {})
    neg_bert = num(allrow.get("negatif")) / num(allrow.get("All")) if allrow else None
    neg_lex = num(ct.get("negatif", {}).get("All")) / num(allrow.get("All")) if allrow and ct.get("negatif") else None
    pos_lex = ct.get("positif", {})
    flip = num(pos_lex.get("negatif")) / num(pos_lex.get("All")) if pos_lex else None
    agree = info.get("overall_agreement_with_lexicon")
    model_name = info.get("model", "[model]")

    val = jload(os.path.join(BASE, "annotation", "validation_result.json"))
    k_llm = (val.get("kappa_llm_qwen3_8b_vs_llm_gemma2_9b") or {}).get("kappa")
    human_ready = not str(val.get("sumber_label_emas", "")).startswith("belum")

    pct = lambda x: f"{x*100:.1f}%" if x is not None else "[n/a]"

    # ---------- teks ----------
    T = []
    A = T.append
    A("# Introduction — Draft\n")
    A(f"_Generated by `./bit intro` on {datetime.datetime.now():%d-%m-%Y %H:%M} WIB. "
      "Numbers are pulled automatically from the latest pipeline outputs; `[CITE: …]` marks where a reference is required._\n")
    A("**Working title:** *The Scream Is a Compliment: Fear-as-Demand Signals and the Pre-Release Prediction of "
      "Indonesian Horror Box Office — Evidence from Soraya Intercine Films*\n")
    A("**Author:** Indri Anjar Kartika Sari\n")
    A("**Project:** SANTET (Sentiment Analysis for Nusantara Theatrical Expectation Tracking) — "
      "*\"reading the netizens' 'incantations' before a film opens.\"*\n")
    A("**Citation (BibTeX):**\n```bibtex\n"
      "@misc{sari2026santet,\n"
      "  author    = {Sari, Indri Anjar Kartika},\n"
      "  title     = {The Scream Is a Compliment: Fear-as-Demand Signals and the Pre-Release Prediction of Indonesian Horror Box Office --- Evidence from Soraya Intercine Films},\n"
      "  year      = {2026},\n"
      "  note      = {Working paper},\n"
      "  url       = {https://github.com/indri007/soraya-film-explorer}\n"
      "}\n```\n")

    A("## 1. Opening hook\n")
    A(f"In 2018, a studio founded in 1982 resurrected a horror icon who had died a decade earlier, and "
      f"{fmt_int(s18)} Indonesians bought tickets to see her. Soraya Intercine Films' *Suzzanna: Bernapas dalam Kubur* "
      f"became one of the highest-grossing Indonesian horror films of all time [CITE: filmindonesia.or.id], and the franchise "
      f"continued with *Suzzanna: Malam Jumat Kliwon* (2023; {fmt_int(s23)} admissions) and *Suzzanna: Santet Dosa di Atas Dosa* "
      f"(2026; {fmt_int(s26)} admissions{'' if s26_final else ', still in release at data collection'}). Yet the same studio, "
      f"working in the same genre with comparable promotional machinery, also released *Racun Sangga* (2024), which drew "
      f"{fmt_int(rs)} admissions{'' if rs_final else ' (provisional figure)'} — roughly {ratio:.1f} times fewer than the 2018 revival. "
      "What separates these outcomes *before either film opens*?\n" if ratio else
      "[Hook: lengkapi angka penonton Suzzanna 2018 dan Racun Sangga di data/films_clean.csv]\n")
    A("Trailers on YouTube offer a candidate answer, but only if they are read correctly. Indonesian audiences praise horror "
      "trailers with comments such as *\"serem banget, merinding parah\"* (\"so scary, total goosebumps\"). Standard sentiment "
      "models read such comments as negative. In horror, however, fear is not rejection; it is the product. **Fear is demand.**\n")

    A("## 2. Context: a horror-dominated market that the literature overlooks\n")
    A("Box office forecasting from online signals is an established research stream, from word-of-mouth volume "
      "[CITE: Liu 2006; Duan, Gu & Whinston 2008] to social media buzz [CITE: Asur & Huberman 2010] and trailer-comment "
      "sentiment [CITE: IEEE 2019 YouTube trailer sentiment index]. This literature, however, is anchored in Hollywood, "
      "Chinese, Korean and Indian markets [CITE: review]. Indonesia — where horror is the commercial backbone of national "
      "cinema [CITE: industry statistics] — is largely absent from high-impact journals, and existing Indonesian studies of "
      "film audiences rely mostly on surveys and PLS-SEM rather than behavioural digital traces [CITE: Indonesian eWOM studies].\n")
    A("Soraya Intercine Films provides an unusually informative anchor case. Active since 1982, it built its reputation on "
      "Suzzanna-era horror, revived that legacy intellectual property after 2018, and operates a horror-focused sub-label, "
      "Hitmaker Studios [CITE: company/press sources]. Its catalogue therefore contains franchise and stand-alone releases "
      "produced under similar organisational conditions, allowing within-studio comparison that controls for production "
      "and distribution capacity — a design rarely used in box office research.\n")

    A("## 3. Three problems with current approaches\n")
    A("**Language (misread fear).** Genre-specific lexical bias in sentiment analysis has been documented for English horror "
      "reviews, which contain more negative words regardless of overall evaluation [CITE: Yale thesis on IMDb genre "
      "generalisation]. Whether the same bias affects Indonesian transformer models, applied to slang-heavy, code-mixed, "
      "emoji-rich YouTube comments, is unknown. Moreover, affective polarity is not the construct of business interest: "
      "what matters is *watch intent* — the stated plan to see the film in a cinema [CITE: purchase-intent literature].\n")
    if n_com and neg_bert is not None:
        A(f"> *Preliminary evidence (to move to Results or keep as motivation):* across {fmt_int(n_com)} trailer comments on "
          f"{n_films} films, the off-the-shelf model `{model_name}` labelled {pct(neg_bert)} of comments as negative, whereas a "
          f"horror-aware lexicon that treats fear words as praise labelled only {pct(neg_lex)} as negative. Among comments the "
          f"lexicon marked positive, {pct(flip)} were classified negative by the transformer (overall agreement {pct(agree)}). "
          + (f"Two local LLM annotators agreed only moderately (κ = {k_llm:.2f}), and " if k_llm is not None else "")
          + ("human gold labels are available for validation." if human_ready else
             "human gold labels are still pending, so this gap is a hypothesis to be validated, not yet a finding.") + "\n")

    A("**Time (contaminated signals).** Many studies correlate cumulative metrics observed after release with final "
      "admissions, which conflates prediction with reaction: a film can accumulate likes *because* it is succeeding "
      "[CITE: endogeneity in box office–buzz studies]. Valid forecasting requires a strict pre-release cutoff (H-14, H-7, H-1). "
      "Public platforms rarely expose historical view or like counts, but comment timestamps and search-interest series can "
      "be reconstructed for any window.\n")
    if likes:
        A(f"> *Preliminary evidence:* cumulative trailer likes correlate with admissions (Spearman ρ = {num(likes.get('rho')):.3f}, "
          f"exact p = {num(likes.get('p_exact')):.3f}, bootstrap 95% CI {likes.get('CI95_bootstrap')}; n = {likes.get('n')}), but the "
          f"association does not survive multiple-testing correction (Benjamini–Hochberg q = {num(likes.get('q_BH')):.2f}) and "
          f"weakens after controlling for release year and franchise status (partial ρ = {num(likes.get('rho_parsial_kontrol_tahun_waralaba')):.3f}). "
          f"Off-the-shelf sentiment shows no meaningful association (|ρ| ≤ {max_sent:.2f}). "
          + (f"Pre-release Google Trends alone yields ρ = {num(tr.get('rho')):.3f}, and a leave-one-out model on that single signal "
             f"(MAPE {mdl.get('MAPE_model_%')}%) does not beat a naive baseline (MAPE {mdl.get('MAPE_baseline_%')}%). "
             if tr and mdl else "")
          + "These null and fragile results are the motivation for the present study: volume and polarity are not enough.\n")

    A("**Community (invisible audiences).** Franchise films may draw on a cohesive base of returning fans whose presence sets "
      "a floor under admissions. Co-commenting networks and community detection [CITE: Blondel et al. 2008 Louvain] can make "
      "this base visible, yet network structure has not been linked to box office in Indonesian cinema, nor compared between "
      "theatrical and streaming success.\n")

    A("## 4. Research gap\n")
    A("To date, no study has jointly examined (i) genre-specific lexical bias in non-English sentiment analysis, (ii) the "
      "distinction between affective polarity and behavioural watch intent, (iii) strict pre-release temporal validity, and "
      "(iv) audience network structure around legacy horror franchises, within a horror-dominated national film market. "
      f"Using Soraya Intercine Films as an anchor case, compared with its horror sub-label Hitmaker Studios and benchmarked against competing studios ({', '.join(studios)}), this study "
      "addresses these gaps under an explicit personal-data-protection framework (Indonesia's Law No. 27/2022) "
      "[CITE: UU PDP]. *(Verify every \"no study\" claim with a PRISMA-style search in Scopus/WoS before submission.)*\n")

    A("## 5. Research questions\n")
    A("- **RQ1 (Language):** To what extent do Indonesian sentiment models misclassify fear expressions as negative in horror "
      "trailer comments, and is a Watch Intent Index a more valid proxy for demand?\n"
      "- **RQ2 (Time):** Which strictly pre-release signals — comment volume, watch intent, search interest — are associated "
      "with admissions, and at which window (H-14, H-7, H-1)?\n"
      "- **RQ3 (Franchise & community):** Do Suzzanna and other franchise films show more cohesive commenter networks and a "
      "more stable audience floor than stand-alone releases, including within the same studio?\n"
      "- **RQ4 (Context):** Does a culturally aware model outperform naive baselines and standard sentiment models, within "
      "Soraya's catalogue and across studios?\n")

    A("## 6. Contributions\n")
    A("1. **Theoretical** — the *fear-as-demand* concept: negative affect as a positive demand signal in genre consumption.\n"
      "2. **Methodological** — a temporally clean pre-release design, including timestamp-based reconstruction of comment signals.\n"
      "3. **Empirical** — a multi-signal study of Indonesia's horror market anchored on a four-decade studio.\n"
      "4. **Open & ethical science** — a pseudonymised, checksummed dataset and a UU PDP–aligned research protocol.\n")

    A("We operationalise this agenda in SANTET (Sentiment Analysis for Nusantara Theatrical Expectation Tracking), "
      "an open research pipeline for reading Indonesian audiences in their own idiom. SANTET is an independent academic "
      "project and is not affiliated with, endorsed by, or sponsored by any studio analysed.\n")

    A("## 7. Paper outline\n")
    A("Section 2 reviews box office forecasting, sentiment bias and audience networks. Section 3 describes data, the temporal "
      "cutoff and the Watch Intent annotation protocol. Section 4 reports results for RQ1–RQ4. Section 5 discusses implications "
      "for producers and for culturally aware NLP, and Section 6 concludes with limitations.\n")

    # ---------- lampiran (ID) ----------
    A("---\n\n## Lampiran (internal, hapus sebelum submit)\n")
    A("**Sumber angka otomatis:**\n" + "\n".join(f"- `{u}`" for u in used) + "\n")
    A("**Catatan kejujuran untuk reviewer:**\n"
      "- Hasil awal belum mendukung prediksi: likes tidak lolos koreksi BH, model Trends belum mengalahkan baseline. "
      "Draf ini membingkainya sebagai *motivasi*, bukan temuan positif.\n"
      "- Klaim bias horor masih hipotesis sampai `annotation_sample.csv` (annotator_1 & annotator_2) terisi ≥ 100 baris "
      "dan `./bit sentiment validate` dijalankan.\n"
      "- Leksikon *mengasumsikan* \"serem/merinding\" = pujian; perbedaan IndoBERT vs leksikon belum membuktikan siapa yang benar.\n"
      "- Angka penonton yang belum final (is_final = 0) ditandai di teks.\n")
    A("**Daftar [CITE] yang harus diisi:** Liu 2006; Duan, Gu & Whinston 2008; Asur & Huberman 2010; studi IEEE 2019 "
      "komentar trailer YouTube; tesis Yale bias genre IMDb; studi eWOM film Indonesia (PLS-SEM); Blondel dkk. 2008; "
      "UU PDP No. 27/2022; sumber profil Soraya & Hitmaker; statistik pangsa genre horor Indonesia.\n")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(T))
    words = sum(len(t.split()) for t in T[:T.index("---\n\n## Lampiran (internal, hapus sebelum submit)\n")])
    print(f"[✓] Draf Introduction ditulis: {os.path.relpath(OUT, BASE)}  (~{words} kata, {n_films} film)")


if __name__ == "__main__":
    main()
